- hosts: all
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Ensure Nginx is running
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Clone Simple-Nginx-Webapp repository
      git:
        repo: https://github.com/ColdFusionX/Simple-Nginx-Webapp.git
        dest: /var/www/html/Simple-Nginx-Webapp
      
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present
    
    - name: Run docker-compose up -d
      command: docker-compose up -d
      args:
        chdir: /var/www/html/Simple-Nginx-Webapp
  
    - name: Create Nginx proxy configuration
      copy:
        dest: /etc/nginx/sites-available/proxy
        content: |
          server {
              listen 80;

              location / {
                  proxy_pass http://localhost:8000;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }

    - name: Enable Nginx proxy configuration
      file:
        src: /etc/nginx/sites-available/proxy
        dest: /etc/nginx/sites-enabled/proxy
        state: link

    - name: Remove default Nginx configuration
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Restart Nginx to apply changes
      service:
        name: nginx
        state: restarted