- hosts: all
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Certbot
      apt:
        name: certbot
        state: present

    - name: Install python3-certbot-nginx
      apt:
        name: python3-certbot-nginx
        state: present

    - name: Obtain SSL certificates
      command: certbot --nginx -d cloudfusion.devopstech.fun --non-interactive --agree-tos --email sankartest132@gmail.com

    - name: Ensure Nginx is running
      service:
        name: nginx
        state: restarted
